name: hardypter
description: A starting point for Dart libraries or applications.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.2

dependencies:
  meta: ^1.9.1
  yak_result: ^2.0.0
  yak_utils: ^2.0.0

dev_dependencies:
  lints: ^2.1.0
  stub: ^2.0.0
  test: ^1.24.2
